### PR TITLE
fix(test): replace validator with test helper in evaluation update tests

### PR DESCRIPTION
**Pull request by julpayne**
## What and why

- fixes the bad commit that had a compilation error

## Type

- [ ] feat
- [ ] fix
- [ ] docs
- [ ] refactor / chore
- [x] test / ci

## Testing

- [x] Tests added or updated
- [x] Tested manually

### CODE REVIEW

**Review by gnaulak-redhat — APPROVED** [review]
LGTM
